<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Promise对象</title>
</head>
<body>
<script>
    // let write = (str) => {
    //     document.write(JSON.stringify(str) + '<br>');
    // };

    /**Promise是异步编程的一种解决方案，它比回调函数和事件更加合理，强大。Promise是一个容器，它里面保存着某个未来才会结束的事件。
     * Promise提供统一的API，各种异步操作可以用同样的方法处理。
     * （1）Promise对象的状态不受外界影响，只有三种状态：Pending，Fullfilled，Rejected。
     * （2）一旦状态改变，就不会再改变，任何时候都可以得到这个结果。Promise对象的状态变化有两种，从Pending变成Fullfilled和从Pending
     * 变成Rejected。一旦状态改变，状态就凝固了，不会再改变。
     * */

    /** 2.基本用法
     * Promise构造函数接受一个函数作为参数，该函数的两个参数分别是resolve和reject。它们是两个参数，由javascript引擎提供。
     * resolve函数的作用是，将Promise对象的状态从未完成变成成功，在异步操作成功时调用，并将异步操作的结果作为参数传递出去；
     * reject函数的作用是，将Promise对象的状态从未完成编程失败，在异步操作失败的时候调用，并将异步操作报错的信息，作为参数传递出去。
     *  */
    // let promise = new Promise((resolve, reject) => {
    // 	if (/** 异步操作成功 */) {
    // 		resolve (value)
    //   } else {
    // 		reject (error)
    //   }
    // })

    /**Promise实例生成以后可以使用then方法分别指定Resolved状态和Rejected状态的回调函数。then方法可以接受两个回调函数。
     * 第一个回调函数是Promise对象状态编程Resolved时调用，第二个是Promise对象状态编程Rejected时调用。其中第二个参数是
     * 可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。*/
    //  promise.then((value) => {
    //    // success
    //  }, (error) => {
    //  	// failure
    //  })

    /** 下面代码中timeout方法返回一个Promise实例，标识一段时间后才会发生的结果。过了指定的时间之后，Promise状态变成Resolved
     * 就会触发then方法绑定指定的回调函数 */
    // function timeout (ms) {
    //     return new Promise((resolve, reject) => {
    //         /*setTimeout方法可以接受三个参数，第一个是要执行的代码或者函数，第二个是毫秒数，后面所有的参数都是给第一个参数（函数）传递的参数*/
    //         setTimeout(resolve, ms, 'done')
    //     })
    // };
    //
    // timeout(1000).then(value => {
    //     console.log(value);
    // });

    /** 下面代码中Promise新建立之后立即执行，所有首先输出的是Promise，然后，then方法指定的回调函数，将在当前脚本所有同步执行完
     * 后才会执行，所以Resolved最后执行。所以代码输出如下：
     * Promise
     * Hi
     * Resolved*/
    // let promise = new Promise((resolve, reject) => {
    //     console.log('Promise');
    //     resolve();
    // });
    // promise.then(() => {
    //     console.log('Resolved');
    // });
    // console.log('Hi');

    /** 下面代码中使用Promise包装了一个图片的异步加载操作。如果加载成功就调用resolve方法，否则调用reject方法 */
    // function loadImageAsync (url) {
    //     return new Promise((resolve, reject) => {
    //         let image = new Image();
    //         console.log(image)
    //         image.onload = function () {
    //             resolve(image);
    //         };
    //         image.onerror = function () {
    //             reject(new Error('Could not load image at ' + url))
    //         };
    //         image.src = url;
    //     })
    // }
    // loadImageAsync('./../images/pic1.jpg').then(image => {
    //     document.body.appendChild(image);
    // });

    /**下面代码中getJSON是对XMLHTTPRequest对象的封装，用于发出一个针对JSON数据的http请求，并返回一个Promise对象。
     * 在getJSON内部，resolve函数和reject函数调用时，都带有参数。
     * 如果调用resolve函数和reject函数时带有参数，那么他们的参数就会被传递给回调函数，reject函数的参数通常是Error对象的实例，
     * 标识抛出错误；*/
    // let getJson1 = function (url) {
    //   let promise = new Promise((resolve, reject) => {
    //   	let client = new XMLHttpRequest();
    //   	client.open('GET', url);
    //   	client.onreadystatechange = handler;
    //   	client.responseType = 'json';
    //   	client.setRequestHeader('Accpt', 'application/json');
    //   	client.send();
    
    //   	function handler () {
    //   		if (this.readyState !== 4) {
    //   			return;
    //       }
    //       if (this.status === 200) {
    //   			resolve(this.response);
    //       } else {
    //   			reject(new Error(this.statusText));
    //       }
    //     }
    //   });
    //   return promise;
    // }
    // getJson1('posts.json').then(json => {
    // 	console.log(json);
    // }, error => {
    //   console.log(`出错了`, error);
    // })

    /**resolve函数的参数除了正常的值以外，还可能是另一个Promise实例，如下。p1, p2都是Promise的实例，但是p2的resolve方法将
     * p1作为参数，即一个异步操作的结果是另一个异步操作。
     * 注意这时p1的状态就会传递给p2，也就是说p1的状态决定了p2的状态。如果p1的状态是pending，那么p2的回调函数就会等待p1的状态
     * 改变；如果p1的状态已经是resolved或者rejected那么p2的回调函数会立即执行*/
    // let p1 = new Promise(function (resolve, reject) {
    //
    // });
    // let p2 = new Promise(function (resolve, reject) {
    //   resolve(p1)
    // })

    /**p1是一个promise，3秒后变成rejected，p2的状态在1秒后改变，resolve方法返回的是p1。由于p2返回的是另一个Promise，导致p2自己的状态
     * 无效了，由p1的状态决定了p2的状态，所以，后面then语句变成针对后者（p1），又过了2秒p1编程rejected，导致触发catch方法指定的回调函数。
     * 调用resolve或者reject并不会终结Promise的参数函数的执行。*/
    var p1 = new Promise((resolve, reject) => {
        setTimeout(() => reject(new Error('fail')), 3000)
    });
    var p2 = new Promise((resolve, reject) => {
        setTimeout(() => resolve(p1), 1000);
    });
    p2.then(result => console.log(result)).catch(error => console.log(error));

    /**下面代码中调用resolve(1)以后，后面的write(2)还是会执行，并且会先打印出来，这是因为立即resolve的Promise是在本轮时间循环的末尾执行，
     * 总是晚于本轮循环的同步任务*/
    // new Promise((resolve, reject) => {
    // 	resolve(1);
    // 	console.log(2);
    // }).then(r => {
    //   console.log(r);
    // });

    /* 一般来说resolve或者reject之后，Promise待使命就完成了，后续操作应该放在then里面，而不是直接放在resolve或者reject后面。
    * 所以，最好在他们前面加上return语句这样就不会有意外,下面代码就不会输出2**/
    //   new Promise((resolve, reject) => {
    //       return resolve(1);
    //       write(2);
    //   }).then(r => {
    //       write(r);
    //   })

    /**3.Promise.prototype.then()
     * 下面代码中采用链式then，可以制定一组按照次序调用的回调函数。这时，前一个回调函数，有可能反悔待还是一个Promise对象，
     * 这时后一个回调函数，就会等待Promise对象待状态发生变化才会被调用。
     * 下面代码中，第一个then方法指定的回调函数，就会等待这个新的Promise对象状态发生变化，如果变成Resolved，就调用funcA，
     * 如果变成Rejected就调funcB
     * */
    let getJson = function (url) {
        let promise = new Promise((resolve, reject) => {
            let client = new XMLHttpRequest();
            client.open('GET', url);
            client.onreadystatechange = handler;
            client.responseType = 'json';
            client.setRequestHeader('Accpt', 'application/json');
            client.send();

            function handler () {
                if (this.readyState !== 4) {
                    return;
                }
                if (this.status === 200) {
                    resolve(this.response);
                } else {
                    reject(new Error(this.statusText));
                }
            }
        });
        return promise;
    }
    // getJson('posts.json').then(function (post) {
    //     return getJson(post.commentURL);
    // }).then(function funcA (comments) {
    //     console.log("Resolved: ", comments);
    // }, function funcB (err) {
    //     console.log("Rejected: ", err);
    // });
    // getJson('posts.json').then(
    //     post => getJson(post.commentURL)
    // ).then(
    //     comments => console.log('resolved', comments),
    //     err => console.log('rejected', err)
    // );


    /**4.Promise.prototype.catch()
     * Promise.prototype.catch方法是then(null, rejection)的别名，用于制定发生错误时待回调*/

    // getJson('posts.json').then(function (posts) {
    //
    // }).catch(error => {
    //     console.log('发生了错误', error)
    // })

    // var p = new Promise((resolve, reject) => {
    //     if (true) {
    //         resolve('fulfilled')
    //     } else {
    //         reject()
    //     }
    // });
    // p.then(val => console.log('fulfilled:', val))
    //     .then(null, err => console.log('rejected:', err))
    // // 等同于
    // p.then(val => console.log('fulfilled:', val))
    //     .catch(err => console.log('rejected', err));
    // const promise1 = new Promise((resolve, reject) => {
    //         try {
    //             throw new Error('test');
    //         } catch (e) {
    //             reject(e)
    //         }
    //     });
    // promise1.catch(error => {
    //     console.log(error);
    // });
    // const promise2 = new Promise((resolve, reject) => {
    //     reject(new Error('text'));
    // })
    // promise2.catch(error => console.log(error));

    // const promise = new Promise((resolve, reject) => {
    //         resolve('ok')
    //         throw new Error('test')
    //     })
    // promise.then(value => console.log(value))
    //     .catch(error => console.log(error))

    // const promise = new Promise((resolve, reject) => {
    //         throw new Error('test')
    //     })
    // promise.catch(error => console.log(error))
    // // 等同于
    // promise.then(null, error => console.log(error))

    // const someAsyncThing = function() {
    //         return new Promise(function(resolve, reject) {
    //             // 下面一行会报错，因为x没有声明
    //             resolve(x + 2);
    //         });
    //     };
    // someAsyncThing().then(function() {
    //     console.log('everything is great');
    // }).catch(e => console.log(e));
    //
    // setTimeout(() => { console.log(123) }, 2000);

    // const promise = new Promise((resolve, reject) => {
    //         resolve('ok')
    //         throw new Error('test')
    //         console.log('test')
    //     })
    // promise.then(value => {
    //     console.log(value)
    // }).catch(e => console.log(e))

    // const someAsyncThing = function () {
    //         return new Promise((resolve, reject) => {
    //             resolve(x + 2)
    //         })
    //     }
    // someAsyncThing().catch(error => console.log('oh on', error))
    //     .then(() => console.log('carry on'))
    // Promise.resolve().catch(error => console.log('oh no', error))
    //     .then(() => console.log('carry on'))
    // const someAsyncThing = function () {
    //         return new Promise(function (resolve, reject) {
    //             // 下面一行会报错，因为x没有声明
    //             resolve(x + 2);
    //         });
    //     };
    // someAsyncThing().then(function () {
    //     return someOtherAsyncThing();
    // }).catch(function (error) {
    //     console.log('oh no', error);
    //     // 下面一行会报错，因为y没有声明
    //     y + 2;
    // }).catch(function (error) {
    //     console.log('carry on', error);
    // });

    // 5. Promise.prototype.finally()
    // Promise.resolve('resolve')
    //     .then(result => console.log(result))
    //     .catch(e => console.log(e))
    //     .finally(() => console.log('finally'))
    // Promise.prototype.finally = function (callback) {
    //     let p = this.constructor
    //     return this.then(
    //         value => P.resolve(callback()).then(() => value),
    //         reason => p.resolve(callback()).then(() => { throw  reason })
    //     )
    // }
    // Promise.resolve(2).then(() => {}, () => {})
    // Promise.resolve(2).finally(() => {})

    /**5.Promise.all()
     * Promise.all方法用于将多个Promise实例包装成一个新的Promise实例，下面代码中Promise.all方法接受一个数组作为参数
     * p1，p2，p3都是Promise实例，如果不是就会先调用下面Promise.resolve方法，将参数转换为Promise实例，再进一步处理。
     * Promise.all方法待参数可以不是数组，但必须具有Iterator借口，且反悔待每个成员都是Promise实例
     * var p = Promise.all([p1, p2, p3]);
     * （1）只有p1，p2，p3的状态都变成fullfilled，p的状态才会变成fullfilled，此时p1，p2，p3的返回值组成一个数组，传递给p
     * 的回调函数。
     * （2）只要p1，p2，p3之中有一个变成Rejected，p的状态就变成rejected，此时第一个被reject待实例返回值，会传递给p待回调函数。
     * */

    // const p1 = new Promise((resolve, reject) => {
    //     resolve('hello');
    // }).then(result => result)
    //     .catch(e => e);
    //
    //
    // const p2 = new Promise((resolve, reject) => {
    //     throw new Error('报错了');
    // }).then(result => result)
    //     .catch(e => e);
    //
    //
    // Promise.all([p1, p2])
    //     .then(result => console.log(result))
    //     .catch(e => console.log(e));

    // const p1 = new Promise((resolve, reject) => {
    //     resolve('hello');
    // }).then(result => result)
    //
    //
    // const p2 = new Promise((resolve, reject) => {
    //     throw new Error('报错了');
    // }).then(result => result)
    //
    //
    // Promise.all([p1, p2])
    //     .then(result => console.log(result))
    //     .catch(e => console.log(e));


    /**6.Promise.race()
     * Promise.race方法同样是将多个Promis实例包装成一个新的Promise实例。下面代码中只要p1,p2,p3之中有一个实例
     * */

    // const p = Promise.race([
    //     fetch('/resource-that-may-take-a-while'),
    //     new Promise(function (resolve, reject) {
    //         setTimeout(() => reject(new Error('request timeout')), 5000)
    //     })
    // ]);
    //
    // p.then(console.log)
    //     .catch(console.error);


    /**7.Promise.resolve()
     * Promise.resolve方法将现有对象转换为Promise对象， 该方法的参数有下面四种类型
     * （1）参数是一个Promise实例，那么Promise.resolve()将不做任何修改，原封不动的返回这个实例。
     * （2）参数是一个thenable对象，（thenable对象是指有then方法的对象），Promise.resolve方法会将这个对象转换为Promise对象，
     * 然后就立即执行thenable对象的then方法。thenable对象的then方法执行之后，对象p1的状态就变为resolve，从而立即执行最后那个then方法
     * 指定的回调函数
     * */

    // let thenable = {
    //     then: function (resolve, reject) {
    //         resolve(42);
    //     }
    // };
    // let p1 = Promise.resolve(thenable);
    // console.log(p1);
    // p1.then(function (value) {
    //     console.log(value);
    //     console.log(p1)
    // });
    // console.log(p1);

    /**(3)从那数不是具有then方法的对象，或者根本不是对象
     * 如果参数是一个原始值，或者是一个不具有then方法的对象，则Promise.resolve方法返回一个新的Promise对象，状态为Resolved
     * 下面代码生成一个新的Promise对象的实例p，由于字符串不属于异步操作（判断方法是字符串对象不具有then方法），返回Promise实例
     * 的状态从一生成就是Resolved，所以回调函数立即执行。Promise.resolve方法的参数，会同时传递给回调函数。*/
   // var p = Promise.resolve('Hello');
   // console.log(p)
   // p.then(function (s) {
   //     console.log(s)
   // })

    /**(4).不带任何参数
     * Promise.resolve方法允许调用时不带参数，直接返回一个Resolved状态的Promise对象，所以如果希望得到一个Promise对象，比较方便的方法
     * 就是直接调用Promise.resolve。
     * 需要注意的是，立即resolve的Promise对象，是在本轮时间循环的结束时，而不是在下一轮事件循环的开始时。
     * 下面代码setTimeout是在下一轮事件循环开始时执行，Promise.resolve是在本轮事件循环结束时执行，console.log则是立即执行*/
    // setTimeout(function () {
    //     console.log('three');
    // }, 0);
    // Promise.resolve().then(function () {
    //     console.log('two');
    // });
    // console.log('one');

    /**8.Promise.reject()
     * Promise.reject(reason)方法也会返回一个新的Promise对象实例，该实例的状态为rejected
     * 下面代码生成一个Promise对象的实例p，状态为rejected，回调函数立即执行。
     * Promise.reject()方法的参数，会原封不动的作为reject的理由，变为后续方法的参数，这一点和Promise.resolve方法不一致
     * */
    // const p = Promise.reject('出错了');
    // //等同于
    // const p = new Promise((resolve, reject) => reject('出错了'))
    // p.then(null, function (s) {
    //     console.log(s);
    // });

    /**下面代码中，Promise.reject方法的参数是一个thenable对象，执行以后，后面catch方法的参数不是reject抛出的“出错了”这个
     * 字符串，而是thenable对象*/
    // const thenable = {
    //     then(resolve, reject) {
    //         reject('出错了');
    //     }
    // };
    // Promise.reject(thenable)
    //     .catch(e => {
    //         console.log(e === thenable)
    //     })

    /**9.两个有用的附加方法
     * ES6的Promise API提供的方法不是很多，有些有用的方法可以自己部署，下面介绍两个不在ES6中，但是很有用的方法。*/
    /**done*/

    // const f = () => console.log('now');
    // Promise.resolve().then(f);
    // console.log('next');
    //
    // const f = () => console.log('now');
    // (async () => f())();
    // console.log("next");

    // const f = () => console.log('now');
    // Promise.try(f);
    // console.log('next');

</script>
</body>
</html>